### ISSUE TITLE
Manuals for the simulators are written in Swedish

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_simulator#10]
The manuals for the simulator has been translated to English, but only the Swedish versions are distributed in the installation package

**Comment by tomasrook** [comment]
I forgot to change what documents to include in the setup script. It has now been changed and will be included in the next release pack.

**Comment by otterdahl** [comment]
Fixed in 70817ebabee983a441eec2828ff3cdac21377827
