### ISSUE TITLE
Alarms has invalid category attribute

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_simulator#11]
According to the rsmp core spec, the 'cat' atributes in alarms must be:

> A character, either T or D.

But the simulator sends alarms with cat set to 'b'.

**Comment by emiltin** [comment]
I suppose this is defined in the SXL it loads?

**Comment by emiltin** [comment]
ping @tomasrook

**Comment by tomasrook** [comment]
Yes, it did not do any validation of the character(s) in the category column. The next release 2 will issue a warning in the syslog and will not use the alarm if the category is not 'T' or 'D'

**Comment by otterdahl** [comment]
Fixed in 1.0.1.5
