### ISSUE TITLE
Fill out "rea" when sending NotAcknowledged

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_simulator#2]
When sending invalid commands to the simulator, it response with NotAcknowledged with empty "rea", even though a reason is shown in the log window in the simulator.

I suggest sending the reason in the "rea" field.

**Comment by tomasrook** [comment]
The error message in the log was not always properly connected to the 'reason' property in the MessageNotAck messages. It has been fixed in next release (hopefully everywhere)

**Comment by otterdahl** [comment]
Fixed in 1.0.1.5
