### ISSUE TITLE
Mixed tabs and spaces for indentation

### ISSUE THREAD

**Issue by jakobht** [rsmp-nordic/rsmp_simulator#25]
Several of the files in the project has mixed tabs and spaces for indentation. This makes the code unreadable in editors where the tab size does not match, see e.g. : 
https://github.com/rsmp-nordic/rsmp_simulator/blob/73327eccb16ac0edf0eb554ce6edf0b1e0c8b1ae/RSMPCommon/RSMPGS_Messages.cs#L73-L110
Where the classes are not indented the same because of this issue.

**Comment by emiltin** [comment]
thank you for opening this issue. for reference, the PR #24 tried to fix this but was hard to review.
