### ISSUE TITLE
Use semantic versioning?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_simulator#28]
The latest release is 1.0.1.7. Is there a reason for using four levels, or could we move to semantic versioning?

http://cucumber.io

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by otterdahl** [comment]
Fixed in latest release
